name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build minified assets
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn gulp build
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: LunaThatBully
